### ISSUE TITLE
Access all headers from Envelope

### ISSUE THREAD

**Issue by ts2909** [jhillyerd/enmime#11]
With the later changes, the headers field of the Envelope has been made private. I have need of all headers in the email and there does not seem to be a way of doing this without knowing ahead of time what they are, and using the GetHeader method.

Do you have a recommended way of doing this, ie perhaps a new HeaderKeys method, make headers public, or a new GetRawHeader method, or perhaps there is something I'm missing?

**Comment by jhillyerd** [comment]
The headers can be accessed through the Root Part: https://github.com/jhillyerd/enmime/blob/master/part.go#L18

I may end up making them public in the Envelope again to support encoding new mail, not sure yet...

**Comment by jhillyerd** [comment]
Thinking along these lines, once thing I noticed when messing around with the example test for the [cmd utils](https://github.com/jhillyerd/enmime/blob/master/cmd/utils.go#L63) package is that textproto.MIMEHeader is a map, so it loses ordering once read.

The way I designed inbucket, it shows the full message source, which it obviously has access to.  Other enmime clients may want to just display the header block, and it seems silly to make them parse that section out of the raw email when enmime already does that.

Do you think it would be useful to have a way to get the raw message header as a block of text (or slice of lines)?

**Comment by jhillyerd** [comment]
Also:  Given you've been in the enmime source, and it wasn't obvious that Envelope.Root held the headers, do I need to better document the Envelope/Part relationship?

I saw a quote the other day that developers are mostly looking for example code to cut & paste when trying out libraries, so maybe I should put together some more examples and link to them from the README.  I'm not sure many developers even know the [current example](https://godoc.org/github.com/jhillyerd/enmime#example-package) even exists.

**Comment by ts2909** [comment]
Funny you mention just needing the headers, I just created a pull request with a fix to parse only the headers. We sometimes pull only the headers from IMAP and just need to parse and decode this.

In our case we don't need to maintain the order of the headers, but I suppose there could be a use case for this, but it's difficult when the standard library functions don't allow this!

One of the first things I do with golang code is look at the example, so I was aware of this.. There isn't anything in there about the Root, or the message headers, besides the GetHeader function, which when you look at it, accesses the private header field. It's not quite clear the Root headers and the same as the Envelope field.

But yeah, good work, it's exactly what I'm looking for, particularly the new work on the Warnings. We need to be as liberal as possible when decoding mail, it's not really an option to just fall over, we need to extract as much as possible.

So some examples which use Warnings, and also, I'm not sure of how that relates to the Envelope Errors slice.. Perhaps another example?

**Comment by jhillyerd** [comment]
Does the example in 95c1169f404cd856e2848c27b5145f6bce92d501 help some?  I think in the end I may need to create some documentation in the Wiki and link to examples.

**Comment by jhillyerd** [comment]
The builder style I used for generating mail didn't require me use expose the header field in Envelope.

Still thinking about the best way to do this.  I worry that just making the header field public would mean users wouldn't notice `GetHeader()`, and would miss out on the decoding it does for them.  As you mention in the initial report, something like a `HeaderKeys()` method may guide them towards using `GetHeader()` as well.

**Comment by requaos** [comment]
@jhillyerd I just wanted to chime in on this thread, because I have a use case where the ordinality of the headers is important (for this task I copy out the header block and match each header key with a key in the map and have it return the first item in the slice as they occur from top to bottom). I have not put a lot of thought into what type of data structure would be best for holding, accessing and populating the headers. As I understand it, SMTP servers only care about presence and not the ordinality of the headers. Having the ability to digest an email into an envelope and then rebuild that email from the envelope (exceptions being that the rebuilt email will follow a consistent convention for headers, folding-whitespace, media-parameters, encoding type, etc.) with a certain degree of exactitude would be useful.

**Comment by N0jja** [comment]
@jhillyerd There's an issue with making the headers private and having to use GetHeader to retrieve the value. 
With an exchange infrastructure, when passing hops, headers with the same key "Recieved" gets added. 
GetHeader only returns a single string for a given header key, where you can have multiple lines with the same key. 
Solution would either be making the headers Public, or return a []string
![Capture](https://user-images.githubusercontent.com/15324584/73825409-42424400-483f-11ea-9936-8ea1d2f51cba.JPG)

**Comment by jhillyerd** [comment]
I think `func (e *Envelope) GetHeaderValues(name string) []string` is what you want, it returns them in the same order as the hidden `header` field after converting to UTF-8.  This was added in #72 - possibly making this issue obsolete.

**Comment by N0jja** [comment]
Ah yes, totally, my bad, it seems I was having a really old release locally, thanks !

**Comment by jhillyerd** [comment]
No problem.

For anyone else that stumbles upon this, either use `Envelope.GetHeaderValues()` (convereted to UTF-8), or `Envelope.Root.Header`(raw)
