### ISSUE TITLE
Add limits to prevent abuse

### ISSUE THREAD

**Issue by akissa** [jhillyerd/enmime#110]
**What I did:**

Investigating the package for use in a email scanning project, looked at the docs and the source.

**What I expected:**

Options to limit the max number of mime parts to be processed and max nested levels to descend.

**What I got:**

Cannot find any limits, meaning memory exhaustion could occur on a message with very many parts.

I suspect you could also run into issues with recursion limits being exceeded for deeply nested messages ?

**Release or branch I am using:**

master

**Comment by jhillyerd** [comment]
enmime doesn't have protection for that.  Given that we hold parsed messages in memory, I think it's more likely we run out of memory with large attachments than run out of stack due to recursion.

Once #90 is implemented, we could have optional limits on parts, part size, and nesting depth.

**Comment by jhillyerd** [comment]
We added error limits, but I don't think there is enough interest in this feature beyond that.
