### ISSUE TITLE
Errors in address format processing without white space

### ISSUE THREAD

**Issue by derktam** [jhillyerd/enmime#112]
**What I did:**
```
...
From: "=?UTF-8?B?7ZWc6rWt642w7J207YSw7KeE7Z2l7JuQ?="<kodb_pr@kdata.or.kr>
...
```
The following problem occurred during testing with the eml file containing the above sender.

When testing with the same data,  
using the ***mail*** package's **mail.ParseAddressList(m.GetHeader("From"))** works correctly,  
but when using **Envelope.AddressList("From")**, a **mail: no angle-addr** error occurs.

**What I expected:**
([]\*Mail.Address) returned without error,

**What I got:**
returned error
**mail: no angle-addr**

**Release or branch I am using:**
both v0.5.0 and master

(Please attach a sample message if you feel it will help reproduce the issue)

**Comment by derktam** [comment]
The address part(<kodb_pr@kdata.or.kr>) disappears after passing through decodeToUTF8Base64Header() in AddressList().

**Comment by jhillyerd** [comment]
Thanks, definitely sounds like a bug.

**Comment by requaos** [comment]
I'll take a look today

**Comment by jhillyerd** [comment]
If easy, we may also want to add a warning to the Errors list.  Not essential.

**Comment by requaos** [comment]
@derktam Could you please confirm if your issue is now resolved using the latest develop branch?

**Comment by derktam** [comment]
It seems to have been resolved. Thank you :)

**Comment by requaos** [comment]
👍
