### ISSUE TITLE
Failed to decode BodyPlainText correctly

### ISSUE THREAD

**Issue by liangyucheng14** [jhillyerd/enmime#131]
What I did:
when I try to parse a mail, it failed to parse the bodyPlainText field due to wrong charset.

What I expected:
I expect the body plain text should be 和弟弟
What I got:
But I got garbled, which is caused by that the library use the charset window-1252, but actually should be utf8.

Release or branch I am using:
master

(Please attach a sample message if you feel it will help reproduce the issue)
MIME-Version: 1.0

Content-Type: multipart/alternative; boundary="000000000000b08cae0591253956"

--000000000000b08cae0591253956
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: base64

5ZKM5byf5byfDQo=
--000000000000b08cae0591253956
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: base64

PGRpdiBkaXI9Imx0ciI+5ZKM5byf5byfPC9kaXY+DQo=
--000000000000b08cae0591253956--

**Comment by jhillyerd** [comment]
We use github.com/saintfish/chardet to detect character set and override what is provided in the Content-Type field if it has a high enough confidence; as Content-Type is often wrong.

I have a feeling that message is too short for it to work well.  We might consider adding a minimum threshold number of characters before we invoke chardet.

**Comment by liangyucheng14** [comment]
Agreed. Maybe the plaintext is too short for the select algorithm to give a right encoding type. My suggestion is that we can consider using Content-Type in the mail if its confidence exceed a threshold, which sound more reasonable than only rely on the select algorithm. 

Anyway, thank you for your response!

**Comment by jhillyerd** [comment]
I believe we are already doing that: https://github.com/jhillyerd/enmime/blob/48138bd64d88b19c499fc8dde63d356f66f5b32d/part.go#L21

May need to research how many characters the chardet algorithm needs to be reliable.

**Comment by requaos** [comment]
Per
https://github.com/jhillyerd/enmime/blob/48138bd64d88b19c499fc8dde63d356f66f5b32d/part.go#L283

I don't think we check the content length against that constant

**Comment by requaos** [comment]
We could check the length of the buffer here:
https://github.com/jhillyerd/enmime/blob/48138bd64d88b19c499fc8dde63d356f66f5b32d/part.go#L181
And if it's not long enough, return a new io.Reader from the unmodified
bytes we just read in.

**Comment by requaos** [comment]
"This is, at best, an imprecise operation using statistics and heuristics. Because of this, detection works best if you supply at least a few hundred bytes of character data that's mostly in a single language." From http://userguide.icu-project.org/conversion/detection
This is the library from which the chardet algorithm was ported.

**Comment by requaos** [comment]
@jhillyerd looks like at least 100 runes long would be a sufficient limit

**Comment by requaos** [comment]
@liangyucheng14 We have merged a fix for this into the `develop` branch. Please use this branch until we cut a release.
