### ISSUE TITLE
PANIC: github.com/jhillyerd/enmime@v0.6.0/header.go:637

### ISSUE THREAD

**Issue by beiping96** [jhillyerd/enmime#134]
```
runtime error: slice bounds out of range 1024 goroutine 5343743 [running]:
panic(0xb55c00, 0x142aff0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/jhillyerd/enmime.rfc2047AttributeName(0xc009828319, 0xa9, 0xc2c6fe, 0x1)
        /home/go/pkg/mod/github.com/jhillyerd/enmime@v0.6.0/header.go:637 +0x94e
github.com/jhillyerd/enmime.fixMangledMediaType(0xc009828300, 0x168, 0xc2c6fc, 0x1, 0x0, 0xd51f40)
        /home/go/pkg/mod/github.com/jhillyerd/enmime@v0.6.0/header.go:298 +0x49c
github.com/jhillyerd/enmime.ParseMediaType(0xc009828300, 0x168, 0xc, 0xc009828300, 0x168, 0x1000, 0xc009683000, 0x0, 0x0, 0xc0003a2700)
        /home/go/pkg/mod/github.com/jhillyerd/enmime@v0.6.0/header.go:231 +0x3cf
github.com/jhillyerd/enmime.(*Part).setupHeaders(0xc0096b6000, 0xc010f66780, 0x0, 0x0, 0x0, 0x0)
        /home/go/pkg/mod/github.com/jhillyerd/enmime@v0.6.0/part.go:116 +0xdc
github.com/jhillyerd/enmime.parseParts(0xc003840200, 0xc01887e7e0, 0xa, 0
```

**Comment by requaos** [comment]
@beiping96 Could you please provide some data to reproduce this?

**Comment by requaos** [comment]
Here is a playground for reproducing this issue: https://play.golang.org/p/fjDiuq5qwVP

**Comment by beiping96** [comment]
https://play.golang.org/p/ghLy5zbMVzC

Here you are

**Comment by requaos** [comment]
@beiping96 have you tested against `develop` branch? This should be resolved by #133

**Comment by pedrinimm** [comment]
@requaos The bug is on the develop branch, method rfc2047AttributeName the error is on referencing indexed on the slice that do not exist.

If you want a string that triggers it here: ?=p?=?

If you isolate the function and pass that as string you have the error.

**Comment by requaos** [comment]
@beiping96 @pedrinimm My mistake, In #133 I introduced a method for replacing `rfc2047AttributeName` functionality without using the same slicing technique. In #136 I actually made the switch.
