### ISSUE TITLE
go test fails from master

### ISSUE THREAD

**Issue by tegk** [jhillyerd/enmime#137]
What I did:
run go test

What I expected:
tests are passing

What I got:
--- FAIL: TestReadHeader (0.00s)
    header_test.go:516: Stripped SID value
        got : "",
        want: "0",
        input: "SID : 0\r\n"
    header_test.go:516: Stripped Audio Mode value
        got : "",
        want: "None",
        input: "Audio Mode : None\r\n"
    header_test.go:516: Stripped Privilege value
        got : "",
        want: "127",
        input: "Privilege : 127\r\n"
FAIL
exit status 1
FAIL	github.com/jhillyerd/enmime	0.042s

Release or branch I am using:
master

**Comment by requaos** [comment]
This is a known issue relating to a bug fix for the textproto package that was introduced in go v1.13.1 and backported to v1.12.10

We have a fix for this in the develop branch
[See merged pull request for details](https://github.com/jhillyerd/enmime/pull/136)

**Comment by tegk** [comment]
would you consider a hot-fix or what is your ETA? I am hesitant to use a library where the tests are not working.

**Comment by jhillyerd** [comment]
I'm traveling, so I can't make any changes for a couple weeks

**Comment by jhillyerd** [comment]
New release has been cut
