### ISSUE TITLE
How to get mime string from Envelope ?

### ISSUE THREAD

**Issue by mvnaz** [jhillyerd/enmime#150]
Hi, thank a lot for useful package!

I create envelope from mime like this:

`envelope, parseError := enmime.ReadEnvelope(strings.NewReader(mime))`

Then I do some manipulation with enveloper, i.e. delete some header:

`envelope.DeleteHeader("some-header")`

Is there a proper way to get back the transformed mime string ? 

Sorry, I don't know the version I use, I got the package yesterday, using :

`go get https://github.com/jhillyerd/enmime`

So I think it should be fresh version..

I took a look here https://github.com/jhillyerd/enmime/issues/7, but I don't see Encode method inside envelope..

Thanks a lot!

**Comment by jhillyerd** [comment]
The envelope is more of a convenience for reading - for outputting you'll want to work with individual Parts.  I don't think changes to the envelope header will actually be reflected in the root part, so try:

```go
root := myEnvelope.Root
root.Header.Del("some-header")
root.Encode(writer)
```
