### ISSUE TITLE
Migrate off of git-flow

### ISSUE THREAD

**Issue by jhillyerd** [jhillyerd/enmime#151]
The git-flow strategy of hiding our mainline in a `develop` branch, and having `master` reflect the most stable release made sense in a pre-Go-modules world.  Now that most projects have adopted Go modules, I don't think we need to protect them from accidentally installing the mainline branch.  Other benefits may include:

- git-flow has been confusing for most new contributors, and they may feel unwelcome when we don't merge their PR to master.
- The inventor of git-flow [noted recently](https://nvie.com/posts/a-successful-git-branching-model/) that it doesn't fit many modern workflows.
- The majority of enhancements to enmime now come from wonderful contributors (big thanks to @dcormier and @requaos), instead of me - my changes should flow through the PR process.
- With git-flow, the project may appear dead if we have not published a stable release in several months.

I propose we switch to the regular [GitHub flow](https://guides.github.com/introduction/flow/) that everyone is used to, and update CONTRIBUTING.md to reflect that.

Let me know if this would break any existing workflows.

**Comment by dcormier** [comment]
I agree with all of this.

**Comment by jhillyerd** [comment]
Given the lack of objections, I plan to make this change on/after May 1st.

**Comment by requaos** [comment]
@jhillyerd I agree as well

**Comment by jhillyerd** [comment]
@requaos good because I was planning to implement tonight! :)
