### ISSUE TITLE
Trailing comma for Content-Type value causes an error

### ISSUE THREAD

**Issue by joekamibeppu** [jhillyerd/enmime#153]
Hi James, thanks for providing and maintaining this great tool! I ran into this while using it and wanted to see what you thought.

What I did: 

Run `enmime.ReadEnvelope()` on a raw email containing the header `Content-Type: text/plain;`. Note the trailing `;` at the end, with nothing following it.

What I expected:

The raw email to be parsed successfully.

What I got:

An error saying, `mime: invalid media parameter`

Release or branch I am using:

Release `v0.8.0`

If this is indeed an issue, I believe I have a small fix ready. I could open a PR against the `develop` branch.

Thanks!

**Comment by dcormier** [comment]
> If this is indeed an issue, I believe I have a small fix ready. I could open a PR against the develop branch.

[Contributions are encouraged.](https://github.com/jhillyerd/enmime/blob/develop/CONTRIBUTING.md)

**Comment by jhillyerd** [comment]
Thanks for reporting Joe!  We'd definitely appreciate a fix, especially if it includes a unit test so we can prevent a regression in the future.
