### ISSUE TITLE
Why force ASCII for filename when the mime.FormatMediaType will encode the filename properly

### ISSUE THREAD

**Issue by vertazzar** [jhillyerd/enmime#155]
https://github.com/jhillyerd/enmime/blob/6eda998e442eb863f7b177f4e7116425504e7c37/encode.go#L107

Forcing ascii should not be done here because ``mime.FormatMediaType`` will do the necessary encoding. 

Unless you found some issues with ``mime.FormatMediaType`` ?

**Comment by jhillyerd** [comment]
It seems in 2018 FormatMediaType did not do what we wanted, see #55 

You could try removing it and see how it affects the unit tests.

**Comment by jhillyerd** [comment]
Do you have a concrete example of how this is causing a problem?  Not sure what to do with issue.

**Comment by vertazzar** [comment]
Hello, sorry for the delay - had a very busy week. I've noticed that for example filename: Field one two three žplpšž (2).xls

becomes  filename*=utf-8''Field%20one%20two%20three%20z%CC%8Cplps%CC%8Cz%CC%8C%20%281%29.xls

Which is what I've been looking for. E-mail clients understand this notation and filename is then displayed correctly. See: https://stackoverflow.com/a/216777/376238

**Comment by pummyiitr** [comment]
new release fix the issue. 
But it is failing on file names when it has semicolon (;) in it. Like abc;xyz.xml, abc;.doc etc.
So pls solve that as well

**Comment by jhillyerd** [comment]
Closing in favor of #174 given primary issue is fixed.
