### ISSUE TITLE
[Missing tests] unhandled invalid chars throwing error in

### ISSUE THREAD

**Issue by pummyiitr** [jhillyerd/enmime#161]
What I did:I am getting thir error while calling enmime.ReadEnvelope method - Failed to ReadParts: mime: invalid media parameter. 

Raw Emails (in attachment part as below) string has some words/chars as =""
So please look into this.

--=_76a4ff3kd56f42bd3djdfdfcfcb4e49c
Content-Transfer-Encoding: base64
Content-ID: <xyz@web.rediffmail.com>
Content-Type: image/png; name="abc.png"; =""
Content-Disposition: inline; filename="abc.png"; 

iVBORw0KGgoAAAANSUhEUgAAAggAAADICAIAAAAC6Y6pAAAACXBIWXMAAAsTAAALEwEAmpwYAAAK
T2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUIIFJCi4AU
kSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuja9a89+bN/rXX
Pues852zzwfACAyWSDNRNYAMqUIeEeCDx8TG4eQuQIEKJHAAEAizZCFz/SMBAPh+PDwrIsAHvgAB
eNMLCADATZvAMByH/w/qQplcAYCEAcB0kThLCIAUAEB6jkKmAEBGAYCdmCZTAKAEAGDLY2LjAFAt
AGAnf+bTAICd+Jl7AQBblCEVAaCRACATZYhEAGg7AKzPVopFAFgwABRmS8Q5ANgtADBJV2ZIALC3

What I expected: The emails must be parsed. I have done same excercise on C#, .net code and it worked without any error for the same email.

What I got: Failed to ReadParts: mime: invalid media parameter. 

Release or branch I am using: master

(Please attach a sample message if you feel it will help reproduce the issue)

**Comment by int01** [comment]
This fix https://github.com/jhillyerd/enmime/issues/162 also will repair this issue.

**Comment by jhillyerd** [comment]
Please retest with master now that #163 is merged.

**Comment by jhillyerd** [comment]
Assigning to myself to create unit tests for this and #162
