### ISSUE TITLE
Huge number of allocations in boundaryReader.Read

### ISSUE THREAD

**Issue by bttrfl** [jhillyerd/enmime#169]
Hi! I found a huge perfomance issue. In the bondaryReader.Read loop, a single byte is copied from one reader to another using CopyN. Internally this allocates a new LimitedReader on every call.
https://github.com/jhillyerd/enmime/blob/2a0b399b27a8c8a689af62304229c0223ad2c9b0/boundary.go#L149
This can be easily seen using pprof. I replaced CopyN with Read/WriteByte methods and this reduced the cpu usage of our production service by a factor of three.

**Comment by dcormier** [comment]
Good catch @bttrfl.

**Comment by bttrfl** [comment]
:+1:
