### ISSUE TITLE
Attachment having semicolon (;) in filenames are not downloading propery. 

### ISSUE THREAD

**Issue by pummyiitr** [jhillyerd/enmime#174]
What I did: attach a file having name like abc;xyz.doc, test;file.txt

What I expected: File should be properly downloaded with complete name.

What I got: File names are coming partially, it is getting broken  at semicolon (;). So I am only getting file-names as abc, test etc. Also extension is not coming. So files are not opening.

Release or branch I am using: version->v0.8.2, commit id->2a0b399

(Please attach a sample message if you feel it will help reproduce the issue)

**Comment by jhillyerd** [comment]
Can you paste in an example part header, so we know what to test with?  Thanks.

**Comment by pummyiitr** [comment]
example is ->
------=_Part_3088737_1836817877.1606818187179
Content-Type: application/octet-stream
Content-Disposition: attachment; filename="holiday~;xyz.png"
Content-Transfer-Encoding: base64

**Comment by jhillyerd** [comment]
Great, #178 should fix that once merged.

**Comment by pummyiitr** [comment]
Did you merge this branch?

**Comment by pummyiitr** [comment]
Please merge this change ASAP as I need that fix urgently.

**Comment by jhillyerd** [comment]
This is now in master branch (not a numbered release), please give it a shot.
