### ISSUE TITLE
Bug in parsing logic of readHeader

### ISSUE THREAD

**Issue by deepakprabhakara** [jhillyerd/enmime#18]
If the header contains fields like "Dkim-Signature" or "Domainkey-Signature" which contain a 'Content-Type:' inside the value then Content-Type header field is parsed wrongly as 'List-Unsubscribe; b=oCvFiVQEh8Fqkfnk9yJ2llkWAnsRxQr8Xf10SjcXK2wrzCXtizroaBbi0FZ7XbHd9fFz03 9UcQ7Vc1EUZ8pAHMG98BRjVaUNuEl2Eqle+NoKi+zRA023xULkCmWzWalclNB/FI5YTEQCpl JBE4+6LWrtWlorhybEDjvi4chJzc0=' instead of 'multipart/alternative; boundary=mimepart_583f950f96b48_6afcdf1038924a'.

Example headers in the email:-
  "headers": {
    "Authentication-Results": "mx.google.com; dkim=pass header.i=@papertrailapp.com; spf=pass (google.com: domain of bounce+beef2e.191099-deepak=redsift.io@papertrailapp.com designates 166.78.70.59 as permitted sender) smtp.mailfrom=bounce+beef2e.191099-deepak=redsift.io@papertrailapp.com",
    "Content-Type": "multipart/alternative; boundary=mimepart_583f950f96b48_6afcdf1038924a",
    "Delivered-To": "deepak@redsift.io",
    "Dkim-Signature": "a=rsa-sha256; v=1; c=relaxed/relaxed; d=papertrailapp.com; q=dns/txt; s=krs; t=1480561936; h=List-Unsubscribe: Content-Type: Mime-Version: Subject: Message-Id: To: From: Date: Sender; bh=Ypk2VpJetOH0wE/ecQUh9usmggXKCYSph2kozqlVh78=; b=oBgHqQb5gL9P21CVXgOUN06ByZHE4Znxnyp3JsIePEzsMDF+Z4nuzKl9CeQA1gv6B3v329Tr W6yRYEXPBPANr2EWcbK9gPUjT33SLckZlvFbaIeEv4/bdCrcr0V7CTBQzMLhXmDuv8xth427 FFlyn2Zy0dWTMFd3UUvp64QrTYc=",
    "Domainkey-Signature": "a=rsa-sha1; c=nofws; d=papertrailapp.com; s=krs; q=dns; h=Sender: Date: From: To: Message-Id: Subject: Mime-Version: Content-Type: List-Unsubscribe; b=oCvFiVQEh8Fqkfnk9yJ2llkWAnsRxQr8Xf10SjcXK2wrzCXtizroaBbi0FZ7XbHd9fFz03 9UcQ7Vc1EUZ8pAHMG98BRjVaUNuEl2Eqle+NoKi+zRA023xULkCmWzWalclNB/FI5YTEQCpl JBE4+6LWrtWlorhybEDjvi4chJzc0=",
    "List-Unsubscribe": "https://papertrailapp.com/account",
    "Message-Id": "<583f950ee15ec_6afcdf103892315@pt02rw04.papertrailapp.com.tmail>",
    "Mime-Version": "1.0",
    "Received": "by 10.31.150.214 with SMTP id y205csp655646vkd; Wed, 30 Nov 2016 19:12:17 -0800 (PST)\nfrom smtp-out.papertrailapp.com (smtp-out.papertrailapp.com. [166.78.70.59]) by mx.google.com with ESMTPS id d12si49552199iof.62.2016.11.30.19.12.16 for <deepak@redsift.io> (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128); Wed, 30 Nov 2016 19:12:16 -0800 (PST)\nfrom papertrailapp.com (pt02rw04.papertrailapp.com [67.214.214.182]) by mxa.mailgun.org with ESMTP id 583f9510.7f4fa0643298-smtp-out-n03; Thu, 01 Dec 2016 03:12:16 -0000 (UTC)",
    "Received-Spf": "pass (google.com: domain of bounce+beef2e.191099-deepak=redsift.io@papertrailapp.com designates 166.78.70.59 as permitted sender) client-ip=166.78.70.59;",
    "Return-Path": "<bounce+beef2e.191099-deepak=redsift.io@papertrailapp.com>",
    "Sender": "support@papertrailapp.com",
    "X-GM-MSGID": "158b85e4ae57c1ba",
    "X-GM-THRID": "158b85e4ae57c1ba",
    "X-Mailgun-Sending-Ip": "166.78.70.59",
    "X-Mailgun-Sid": "WyI3YjEyNCIsICJkZWVwYWtAcmVkc2lmdC5pbyIsICIxOTEwOTkiXQ==",
    "X-Received": "by 10.36.101.5 with SMTP id u5mr31628139itb.45.1480561936981; Wed, 30 Nov 2016 19:12:16 -0800 (PST)",
    "X-Report-Abuse-To": "support@papertrailapp.com"
  }

**Comment by deepakprabhakara** [comment]
This parses fine in go.enmime though.

**Comment by jhillyerd** [comment]
If you have a minute to test, could you checkout 2856163557872230f83c940122eb76ce0c146298 and see if it works?  I suspect f529916313998ce72a7e01ce863a86218b6ac07f may have introduced it, but with so much work on the header parsing since go.enmime, tough to know.  Thanks.

**Comment by deepakprabhakara** [comment]
@jhillyerd Spot on, it works with checkout 2856163.

**Comment by jhillyerd** [comment]
I tried to reproduce with the following:

[ctype-bug.txt](https://github.com/jhillyerd/enmime/files/679361/ctype-bug.txt)

But mime-dump seems to parse and render it correctly below; good content type and it was able to find both text and HTML parts.

I've created a branch named `read-ctype-bug` to work on a fix, could you submit a PR with a failing test case to it?  If possible pair the headers down to the minimum to repro the bug, that will make it a little easier on me.

ctype-bug.txt
=============

## Header
    Authentication-Results: mx.google.com; dkim=pass header.i=@papertrailapp.com; spf=pass (google.com: domain of bounce+beef2e.191099-deepak=redsift.io@papertrailapp.com designates 166.78.70.59 as permitted sender) smtp.mailfrom=bounce+beef2e.191099-deepak=redsift.io@papertrailapp.com
    Content-Type: multipart/alternative; boundary=mimepart_583f950f96b48_6afcdf1038924a
    Delivered-To: deepak@redsift.io
    Dkim-Signature: a=rsa-sha256; v=1; c=relaxed/relaxed; d=papertrailapp.com; q=dns/txt; s=krs; t=1480561936; h=List-Unsubscribe: Content-Type: Mime-Version: Subject: Message-Id: To: From: Date: Sender; bh=Ypk2VpJetOH0wE/ecQUh9usmggXKCYSph2kozqlVh78=; b=oBgHqQb5gL9P21CVXgOUN06ByZHE4Znxnyp3JsIePEzsMDF+Z4nuzKl9CeQA1gv6B3v329Tr W6yRYEXPBPANr2EWcbK9gPUjT33SLckZlvFbaIeEv4/bdCrcr0V7CTBQzMLhXmDuv8xth427 FFlyn2Zy0dWTMFd3UUvp64QrTYc=
    Domainkey-Signature: a=rsa-sha1; c=nofws; d=papertrailapp.com; s=krs; q=dns; h=Sender: Date: From: To: Message-Id: Subject: Mime-Version: Content-Type: List-Unsubscribe; b=oCvFiVQEh8Fqkfnk9yJ2llkWAnsRxQr8Xf10SjcXK2wrzCXtizroaBbi0FZ7XbHd9fFz03 9UcQ7Vc1EUZ8pAHMG98BRjVaUNuEl2Eqle+NoKi+zRA023xULkCmWzWalclNB/FI5YTEQCpl JBE4+6LWrtWlorhybEDjvi4chJzc0=
    List-Unsubscribe: https://papertrailapp.com/account
    Message-Id: 583f950ee15ec_6afcdf103892315@pt02rw04.papertrailapp.com.tmail
    Mime-Version: 1.0
    Received: by 10.31.150.214 with SMTP id y205csp655646vkd; Wed, 30 Nov 2016 ... 
    Received-Spf: pass (google.com: domain of bounce+beef2e.191099-deepak=redsift.io@papertrailapp.com designates 166.78.70.59 as permitted sender) client-ip=166.78.70.59;
    Return-Path: bounce+beef2e.191099-deepak=redsift.io@papertrailapp.com
    Sender: support@papertrailapp.com
    X-Gm-Msgid: 158b85e4ae57c1ba
    X-Gm-Thrid: 158b85e4ae57c1ba
    X-Mailgun-Sending-Ip: 166.78.70.59
    X-Mailgun-Sid: WyI3YjEyNCIsICJkZWVwYWtAcmVkc2lmdC5pbyIsICIxOTEwOTkiXQ==
    X-Received: by 10.36.101.5 with SMTP id u5mr31628139itb.45.1480561936981; Wed, 30 Nov 2016 19:12:16 -0800 (PST)
    X-Report-Abuse-To: support@papertrailapp.com

## Envelope
### Delivered-To
-  `<deepak@redsift.io>`

### Subject


## Body Text
This is a test email

## Body HTML
This is the test HTML

## Attachment List

## MIME Part Tree
    multipart/alternative
    |-- text/plain
    `-- text/html

**Comment by deepakprabhakara** [comment]
Thanks, I'll run this again against my emails and extract out a test case.

**Comment by jhillyerd** [comment]
Thanks for the test case. Looks like Tom's contribution moved the test for a header line starting with a space too late for it to work correctly.  I'm going to push a fix momentarily.

Also, Go has a convention when writing unit test failure messages:  The got/received value should come before the wanted/expected value.  Kinda of nit-picky but it is in a few style guides:

https://github.com/golang/go/wiki/CodeReviewComments#useful-test-failures

**Comment by deepakprabhakara** [comment]
@jhillyerd Thanks, always good to be nit-picky about conventions (especially in Go). 👍
