### ISSUE TITLE
ReadEnvelope fails for large string in a single line.

### ISSUE THREAD

**Issue by shamimevatix** [jhillyerd/enmime#185]
What I did:
Run TestParseMimeTree with the file
https://www.mediafire.com/file/27w6hosijzd85pi/Get_started_with_OneDrive.eml/file
.

What I expected:
no error and HTML, text, attachments of email.

What I got:
envelope_test.go:87: Failed to parse MIME: Failed to ReadParts: multiple Read calls return no data or error

Release or branch I am using:
master branch. commit no: 6b038639b93ca41ddebf246745595190bd22d491

(Please attach a sample message if you feel it will help reproduce the issue)
Check parseParts method. The buffer is getting full. If we shorten or delete line#152 of Get_started_with_OneDrive.eml. Everything works.

Thanks

**Comment by shamimevatix** [comment]
Not a solution, but a workaround so that someone can save his job/work for now.

import (
	"github.com/jhillyerd/enmime"
	"github.com/yosssi/gohtml"
	"strings"
)

func EnMimeReadEnvelopeRetry(byteData []byte) (*enmime.Envelope, error) {
	r := strings.NewReader(string(byteData))
	msgEnvelop, err := enmime.ReadEnvelope(r)
	if err != nil && isReadPartsError(err) {
		formattedHtml := gohtml.Format(string(byteData))
		formattedHtmlReader := strings.NewReader(formattedHtml)
		return enmime.ReadEnvelope(formattedHtmlReader)
	}

	return msgEnvelop, err
}

func isReadPartsError(err error) bool {
	return strings.Contains(err.Error(), "multiple Read calls return no data or error")
}

	return msgEnvelop, err
}

**Comment by jhillyerd** [comment]
I would have expected #200 to fix this, but it did not.

I found if I remove most of the headers, *or* most of the body, it will pass.  Stack trace points to charset conversion:

```
Failed to read envelope:
multiple Read calls return no data or error
github.com/jhillyerd/enmime.(*Part).convertFromDetectedCharset
        /home/james/devel/enmime/part.go:178
github.com/jhillyerd/enmime.(*Part).decodeContent
        /home/james/devel/enmime/part.go:278
github.com/jhillyerd/enmime.parseParts
        /home/james/devel/enmime/part.go:404
github.com/jhillyerd/enmime.parseParts
        /home/james/devel/enmime/part.go:409
github.com/jhillyerd/enmime.ReadParts
        /home/james/devel/enmime/part.go:358
github.com/jhillyerd/enmime.ReadEnvelope
        /home/james/devel/enmime/envelope.go:156
main.(*dumper).dump
        /home/james/devel/enmime/cmd/mime-dump/mime-dump.go:47
```

**Comment by jhillyerd** [comment]
There are two failures at play, the first is that *for this email* Go's quotedprintable reader will call Read on our qpcleaner multiple times with a destination buffer size of 3 bytes, which we do not handle: https://github.com/jhillyerd/enmime/blob/3d1c119b04d860d4e075ecf4926745a06d2ce103/internal/coding/quotedprint.go#L28

I've fixed this locally, but it still leads to a buffer full error.  I'll investigate splitting long qp-encoded lines next.

**Comment by shamimevatix** [comment]
Thanks you so much for making time for this issue. I wish I could help a bit.
