### ISSUE TITLE
MailBuilder Validation for To/CC/BCC()

### ISSUE THREAD

**Issue by jawr** [jhillyerd/enmime#186]
MailBuilder.Build() does some validation around To/CC/BCC here:

https://github.com/jhillyerd/enmime/blob/master/builder.go#L221

However, calling MailBuilder.To/CC/BCC() with a blank address appends an empty struct which then circumvents the validation. Should there be some sort validation on To/CC/BCC() to prevent this, or is it the callers responsibility?

**Comment by jhillyerd** [comment]
If we can do that validation inexpensively, then I'm in favor of adding it.

**Comment by jawr** [comment]
My immediate thought is to just check for length and maybe '@' on the addr string. I don't think it's enmimes job to do much more than prevent emails with a blank To going out. If that's agreeable I'll make a PR.

**Comment by jhillyerd** [comment]
Addresses don't always need an @ sign, so we shouldn't enforce that.  Length sounds good to me, thanks.
