### ISSUE TITLE
Content-Type with option charset="utf-8" confuses parser

### ISSUE THREAD

**Issue by jimidle** [jhillyerd/enmime#204]
What I did:

Parse envelope with text/plain part of email body in standard UTF-8, but the Content-Type option specifies:

`'text/plain; charset="utf-8"'`

and also the same for the HTML alternative.

I.E lower case.

What I expected:

Parser realizes that utf-8 == UTF-8

What I got:

![image](https://user-images.githubusercontent.com/1309104/127764162-71b9086d-a6cc-4ac7-81d9-f03d5903da6f.png)
![image](https://user-images.githubusercontent.com/1309104/127764223-74e9a746-8233-4d31-913d-ea92bf6186b4.png)

Release or branch I am using:

	github.com/jhillyerd/enmime v0.9.0

(Please attach a sample message if you feel it will help reproduce the issue)

Unfortunately, the email isnon-public, but this is easily reproducible by adding the charset option to any email.

**Comment by jhillyerd** [comment]
So you are saying the line:

```
Content-Type: 'text/plain; charset="utf-8"'
```

is this in the main header of the email, or one of the mime parts?

If you have the time, please retest with 0.9.1, we made some fixes although I'm not sure they will affect this.

**Comment by jimidle** [comment]
Using 0.9.1 did not make a difference, but thanks for pointing out the bug fix version. Here are the headers that will reproduce this - basically maybe the encoding should be checked in both upper and lower case.

Main header, followed by the text/plain alternative - you can see it is the alternative mime part that is tagged like this.

```
MIME-Version: 1.0
Content-Type: multipart/related;
	type="text/html";
	boundary="b1_1561be5af646cbba541325697861be86"
X-SG-EID: WztNR2PRomLcfqBK+RerxWJ4rAup134PO8Rq1qNuhavDje8zGBk+OTq/NY1dRB6/Nq0RIQaJCad0OR
 217GZ/P7Y7eB9ny4HxmK1Hlb+8VZVD2E0QQFUKXCx1wfu8n+xptjmFf3nWdw/xReAVrTn1bc2sdVmL
 rhg/rGsZSKIfuGi3evC5IgPD3OFDF786HJ/v3ohsJUApBiEOqPrD6KxPHiJd8gybmND//wHM4WNBIc
 Q=
X-Entity-ID: Mx3tYwNnsT2ZPK1J7a/n7w==

--b1_1561be5af646cbba541325697861be86
Content-Type: multipart/alternative;
	boundary="b2_1561be5af646cbba541325697861be86"

--b2_1561be5af646cbba541325697861be86
Content-Type: text/plain; charset = "utf-8"
content-transfer-encoding: quoted-printable
```

The html part is also tagged with lower case utf8:

```

--b2_1561be5af646cbba541325697861be86
Content-Type: text/html; charset = "utf-8"
content-transfer-encoding: quoted-printable
```

I also note that "us-ascii" will generate a warning as the code will detect an ISO encoding. Perhaps it is OK to warn there, but they are equivalent in email.

**Comment by jhillyerd** [comment]
Playing with this a bit, it only manifests when utf-8 is quoted, and there is a space after the equals sign.
