### ISSUE TITLE
May I ask how to convert from Envelope to mime string?

### ISSUE THREAD

**Issue by 81981266** [jhillyerd/enmime#221]
After getting **Envelope** with **ReadEnvelope**,  I edit some headers. Then, how to convert from Envelope to **mime string**?
Thank you.

**Comment by jhillyerd** [comment]
There is a request for this in #158 -- for now you need to get `envelope.Root` and call `Encode `on it.   I think you also need to manipulate headers on the root part, and not the envelope for them to be output.

**Comment by 81981266** [comment]
The Envelop also can have **Attachments**. How to include _attachment Base64 strings_ to the finial mime string?

**Comment by jhillyerd** [comment]
There isn't a friendly way to do it, but you can see how the builder code creates a new `Part `for attachments here: https://github.com/jhillyerd/enmime/blob/master/builder.go#L154.  You can then call `AddChild` on your root part.
