### ISSUE TITLE
Not an issue, just a thank you

### ISSUE THREAD

**Issue by mholt** [jhillyerd/enmime#226]
Just wanted to say thank you for this library. :pray: I've written a fair amount of parsers but mail messages have been some of the worst I've had to deal with, and this package has taken away all the pain points.

**Comment by jhillyerd** [comment]
Thank you, glad it is useful!  A lot of credit goes to our contributors, as they've rewritten large swathes of enmime to handle all the poorly encoded mail out there. :)

**Comment by mholt** [comment]
Yeah, that's great. I'm using it for [Timelinize](https://twitter.com/timelinize), the successor to https://github.com/mholt/timeliner, for archiving personal emails.
