### ISSUE TITLE
mail: no angle-addr

### ISSUE THREAD

**Issue by c0de9en** [jhillyerd/enmime#227]
What I did:
./mime-extractor -f test.eml -o /tmp

What I expected:
success

What I got:
    X-D57d3aed: 3ZO7eAau8CL7WIMRKs4sN3D3mail: no angle-addr

grep 3ZO7 test.eml
X-D57D3AED: 3ZO7eAau8CL7WIMRKs4sN3D3tLDjz0dLbV79QFUyzQ2Ujvy7cMT6pYYqY16iZVKkSc3dCLJ7zSJH7+u4VD18S7Vl4ZUrpaVfd2+vE6kuoey4m4VkSEu530nj6fImhcD4MUrOEAnl0W826KZ9Q+tr5+wYjsrrSY/u8Y3PrTqANeitKFiSd6Yd7yPpbiiZ/d5BsxIjK0jGQgCHUM3Ry2Lt2G3MDkMauH3h0dBdQGj+BB/iPzQYh7XS329fgu+/vnDheyclF27d65KknI9PbYhapw==

Release or branch I am using:
master

(Please attach a sample message if you feel it will help reproduce the issue)

**Comment by c0de9en** [comment]
Is it possible to ignore the "no angle-addr" error?

**Comment by c0de9en** [comment]
Well, as usual, errors is not where we search it.
This header raises exception:
`To: =?utf-8?Q?=D0=9D=D0=94=D0=A4=D0=9B=D0=BA=D0=B0=20?=<support@qwerty.asdfg>`

Here is no error:
`To: =?utf-8?Q?=D0=9D=D0=94=D0=A4=D0=9B=D0=BA=D0=B0=20?= <support@qwerty.asdfg>`

In other words you estimate a space before "<" but there is no space.

**Comment by c0de9en** [comment]
Exactly the "?=<" raises error

**Comment by jhillyerd** [comment]
Without investigating, I suspect we are decoding the quote-encoded word and appending the bracketed address without a space, then passing it to the golang standard library address parser, which errors out.

If I remember right, the rfcs state that there should be whitespace separating quoted words, which would make this email out of spec.  But I don't think it would be hard to insert the space here, we do plenty of other address fixups.

**Comment by c0de9en** [comment]
Not QP-encoded strings only. I tried messages with Base64-encoded headers too.

**Comment by jhillyerd** [comment]
Looks like this was fixed by #234 but I added a test for it.
