### ISSUE TITLE
Ability to turn off extra processings, e.g. html2text.FromString

### ISSUE THREAD

**Issue by kadukf-outreach** [jhillyerd/enmime#231]
What I did:
Parsing a mime without text/plain part. Field `Text` on the envelope returns a text using html2text converter. This processing is consuming memory as well as CPU. Would it be possible, e.g. using options, to manage this extra work? By default ON, but having a possiblity to turn it OFF but still reporting  ErrorPlainTextFromHTML.

What I expected:
Empty text.

What I got:
Text converted by html2text.

Release or branch I am using:
master

(Please attach a sample message if you feel it will help reproduce the issue)

**Comment by jhillyerd** [comment]
Yeah, this would be a good use of options, blocked by #90

**Comment by jhillyerd** [comment]
Closed by #334
