### ISSUE TITLE
Field accessors for MailBuilder

### ISSUE THREAD

**Issue by andylibrian** [jhillyerd/enmime#260]
Hi, thanks for the project. It's really helpful.

## What I want to do:

I want to access MailBuilder fields from other functions. Apparently the fields are private and there is no accessor available.

```go
func SendEmail(mail *enmime.MailBuilder) error {
        bcc := mail.GetBcc()
}
```

## What I expected:

I would like to access the fields before / without building the MIME part.

## What I got:

No function

## Release or branch I am using:

master

## Note

If you agree to support this, I'm interested to submit a PR to implement it

**Comment by jhillyerd** [comment]
Sure, I'd accept a PR to add getter funcs.
