### ISSUE TITLE
Character decoding characters of other written languages for .Text

### ISSUE THREAD

**Issue by axllent** [jhillyerd/enmime#266]
What I did: I tried to parse an email containing Japanese, Chinese, or Korean in subject and body text

What I expected: Subject and body text to return the same value encoded correctly

What I got: enmime.Text returns an incorrectly-encoded value . The subject however is correctly encoded.

Release or branch I am using: v0.10.1

A working example of the issue can be seen on: https://play.golang.com/p/Uf8QILv488u

**Comment by pedrinimm** [comment]
Why would you expect the correct encoding?

Your email doesn't have the conten-type header with no charset define?

Have you tried actually testing which charset is detected by the library and to which it tries to convert the content?

If you specify actually on your sample the utf-8 charset and the and the header, the parsing works
https://play.golang.com/p/M6A0RlQx_oE

**Comment by axllent** [comment]
Thank you both, I think you have actually answered my question here - I just found https://www.w3.org/Protocols/rfc1341/7_1_Text.html which states `The default Content-Type for Internet mail is "text/plain; charset=us-ascii"` (I assumed this was UTF8). Sorry for the "issue", I'll mark this as resolved, thanks again :)
