### ISSUE TITLE
Delivery Status Notification parsing (bounce messages)

### ISSUE THREAD

**Issue by dmytrokasianenko-outreach** [jhillyerd/enmime#267]
Hi James, we have code for parsing of Delivery Status Notification (DSN) per [rfc3464](https://datatracker.ietf.org/doc/html/rfc3464) and [rfc6522](https://datatracker.ietf.org/doc/html/rfc6522) (also known as [bounce message](https://en.wikipedia.org/wiki/Bounce_message)). I can add this parsing logic here. Do you think this kind of logic belongs to enmime or enmime would benefit from it?

**Comment by jhillyerd** [comment]
Yes, that does sound like a useful addition!
