### ISSUE TITLE
Missing Content-Type maybe shouldn't be a warning/error?

### ISSUE THREAD

**Issue by sporkmonger** [jhillyerd/enmime#27]
> 5.2.  Content-Type Defaults
>
>   Default RFC 822 messages without a MIME Content-Type header are taken
>   by this protocol to be plain text in the US-ASCII character set,
>   which can be explicitly specified as:
>
>     Content-type: text/plain; charset=us-ascii
>
>   This default is assumed if no Content-Type header field is specified.
>   It is also recommend that this default be assumed when a
>   syntactically invalid Content-Type header field is encountered. In
>   the presence of a MIME-Version header field and the absence of any
>   Content-Type header field, a receiving User Agent can also assume
>   that plain US-ASCII text was the sender's intent.  Plain US-ASCII
>   text may still be assumed in the absence of a MIME-Version or the
>   presence of an syntactically invalid Content-Type header field, but
>   the sender's intent might have been otherwise.

**Comment by jhillyerd** [comment]
Nice catch.  So the way I read that is that it only applies to the email message header (Root Part in enmime parlance) - but that all sub-parts should have a Content-Type.  Does that sound correct?

**Comment by sporkmonger** [comment]
Haven't looked into sub-parts, but yeah, I'd definitely read it as
not-required at root.

**Comment by els0r** [comment]
@jhillyerd : how large of a change to the parser would this be? Attached is a sample that results in the above error when parsing it. It's taken from the godoc of `net/mail`.
[simple_no_content_type.sample.txt](https://github.com/jhillyerd/enmime/files/1161624/simple_no_content_type.sample.txt)

**Comment by jhillyerd** [comment]
I think a fairly small change here: https://github.com/jhillyerd/enmime/blob/b6ea5237e7d1fe39d470345ed9b2636a182bfece/part.go#L146

It doesn't look liked ReadParts is used recursively, so removing the warning and return err there should not impact parsing of parts deeper in the message.
