### ISSUE TITLE
Export coding package?

### ISSUE THREAD

**Issue by usedbytes** [jhillyerd/enmime#277]
What I did:

Tried to decode RFC2047 headers

What I expected:

To be able to use the comprehensive RFC2047 decoder in `internal/coding`

What I got:

Unable to import internal module.

I see that the `internal/coding` package was made in #212, but the functionality looks extremely useful (and would solve a use-case for me). I see that I can access decoded headers via `Envelope.GetHeader()`/`DecodeHeaders()`, but what I really need is just `coding.RFC2047Decode()` rather than populating an `Envelope` or parsing from `[]byte`.

Is there a strong reason for `coding` being internal, and/or would you consider exposing `RFC2047Decode()` in a non-internal package?

Thanks for your work on `enmime`! It's saved me a lot of head-scratching.

**Comment by jhillyerd** [comment]
Yeah, I'd be OK with having  `enmime.RFC2047Decode` (or perhaps DecodeRFC2047) that calls the internal package.  I don't want to expose the rest of it though.
