### ISSUE TITLE
Headers with newline separation

### ISSUE THREAD

**Issue by jackhold** [jhillyerd/enmime#28]
I need a little help getting information from the Header below, as you can see there are newline separation between header fields, the purpose is to get the status and the Diagnostic-Code field.
```
--1489
Content-Description: Delivery report
Content-Type: message/delivery-status

Reporting-MTA: dns; host1337
X-Postfix-Queue-ID: 1489
X-Postfix-Sender: rfc822; bounces@XXX.com
Arrival-Date: Wed, 4 May 2017 15:21:18 +0200 (EST)

Final-Recipient: rfc822; XXX@gmail.com
Original-Recipient: rfc822;XXX@gmail.com
Action: failed
Status: 4.2.1
Diagnostic-Code: something went
    wrong
--1489
```
The problem right now is that it stopes looking for header fields when it encounters a empty newline, so the fields that i need is not in the *Part variable, if i remove the empty line's manually it work's. 

(The mail comes directly from a postfix that received it from google.)

And the code i am using to get the information.
```
r := strings.NewReader(Mailcontent_String)
env, err := enmime.ReadEnvelope(r)
if err != nil {
	fmt.Print(err)
}
part2 := env.Root.FirstChild.NextSibling
fmt.Println(part2.Header)
```

**Comment by jhillyerd** [comment]
Headers are terminated by a blank line, the parts you are interested in are actually the body of the message.

From https://tools.ietf.org/html/rfc3464 section 2.1:

> The body of a message/delivery-status consists of one or more "fields" formatted according to the ABNF of RFC 822 header "fields" (see [RFC822]).

**Comment by jackhold** [comment]
First sorry for the late response, second  i did not know about that, would it be possible to use enmime to get the information?? right now i am using regex on the whole mail to get the information that i want, and i think it's a little slow compared to enmime.

**Comment by jhillyerd** [comment]
Apologies for slow response.  Enmime probably wouldn't parse the headers inside the message body well.  Golang does have some tools for that, not sure where they live off the top of my head.
