### ISSUE TITLE
Attachment not detected

### ISSUE THREAD

**Issue by adrium** [jhillyerd/enmime#287]
**What I did:**

Sent the below email to an Inbucket instance.
I received something like that 

```
Subject: Hello World
From: "sender@example.com" <sender@example.com>
To: "recipient@example.com" <recipient@example.com>
Cc: "recipient@example.com" <recipient@example.com>
Message-ID: <1234@example.com>
Date: Fri, 16 Dec 2022 13:00:00 +0000
Content-Type: multipart/mixed; boundary=boundary1

--boundary1
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable

<!DOCTYPE html>
<html>
<head>
<title>Hello World HTML</title>
</head>
<body>
<h1 style=3D"color:red">Hello World</h1>
</body>
</html>

--boundary1
Content-Type: application/pdf; name=Hello-World.pdf
Content-Transfer-Encoding: base64
Content-Disposition: inline; name=Hello-World.pdf;
 filename=Hello-World.pdf

JVBERi0xLjQKJcK1wrYKCjEgMCBvYmoKPDwvVGl0bGUoSGVsbG8gV29ybGQpL0F1dGhvcihBZHJp
dW0pPj4KZW5kb2JqCgoyIDAgb2JqCjw8L1R5cGUvQ2F0YWxvZy9QYWdlcyAzIDAgUj4+CmVuZG9i
agoKMyAwIG9iago8PC9UeXBlL1BhZ2VzL01lZGlhQm94WzAgMCA1OTUgODQyXS9SZXNvdXJjZXM8
PC9Gb250PDwvRjEgNCAwIFI+Pi9Qcm9jU2V0Wy9QREYvVGV4dF0+Pi9LaWRzWzUgMCBSXS9Db3Vu
dCAxPj4KZW5kb2JqCgo0IDAgb2JqCjw8L1R5cGUvRm9udC9TdWJ0eXBlL1R5cGUxL0Jhc2VGb250
L0hlbHZldGljYS9FbmNvZGluZy9XaW5BbnNpRW5jb2Rpbmc+PgplbmRvYmoKCjUgMCBvYmoKPDwv
VHlwZS9QYWdlL1BhcmVudCAzIDAgUi9Db250ZW50cyA2IDAgUj4+CmVuZG9iagoKNiAwIG9iago8
PC9MZW5ndGggNTEvRmlsdGVyL0ZsYXRlRGVjb2RlPj4Kc3RyZWFtCnic03czVDCxUAhJ43IK4TI3
UjA3MVMISeHS8EjNyclXCM8vyknRVAjJ4nIN4QIA3FcKuwplbmRzdHJlYW0KZW5kb2JqCgp4cmVm
CjAgNwowMDAwMDAwMDAwIDY1NTM2IGYgCjAwMDAwMDAwMTYgMDAwMDAgbiAKMDAwMDAwMDA3MSAw
MDAwMCBuIAowMDAwMDAwMTE3IDAwMDAwIG4gCjAwMDAwMDAyNDIgMDAwMDAgbiAKMDAwMDAwMDMz
MSAwMDAwMCBuIAowMDAwMDAwMzkwIDAwMDAwIG4gCgp0cmFpbGVyCjw8L1NpemUgNy9JbmZvIDEg
MCBSL1Jvb3QgMiAwIFI+PgpzdGFydHhyZWYKNTA5CiUlRU9GCg==


--boundary1--
```

**What I expected:**

E-Mail with attachment.

![expected](https://user-images.githubusercontent.com/23739584/228335420-11661cc2-4f20-4c9f-9e36-847e4231ffdb.png)

**What I got:**

Attachment is not displayed.

![actual](https://user-images.githubusercontent.com/23739584/228335449-8880fcc8-12c7-4f16-af9d-95e99055fa30.png)

**Release or branch I am using:**

tested via Inbucket 3.1.0-beta1

**Comment by jhillyerd** [comment]
It looks like this is probably an Inbucket bug, enmime output for your sample above does find the inline attachment.  Likely Inbucket is ignoring inlines.

test.eml
========

## Header
    Content-Type: multipart/mixed; boundary=boundary1
    Date: Fri, 16 Dec 2022 13:00:00 +0000
    Message-Id: <1234@example.com>

## Envelope
### From
- sender@example.com `<sender@example.com>`

### To
- recipient@example.com `<recipient@example.com>`

### Cc
- recipient@example.com `<recipient@example.com>`

### Subject
Hello World

## Body Text
***********
Hello World
***********

## Body HTML
<!DOCTYPE html>
<html>
<head>
<title>Hello World HTML</title>
</head>
<body>
<h1 style="color:red">Hello World</h1>
</body>
</html>


## Attachment List

## Inline List
- Hello-World.pdf (application/pdf)

## Other Part List

## MIME Part Tree
    multipart/mixed (errors: 1)
    |-- text/html
    `-- application/pdf, disposition: inline, filename: "Hello-World.pdf"

## Errors
- [W] Plain Text from HTML: Message did not contain a text/plain part

**Comment by adrium** [comment]
Thanks for the analysis. Due to `disposition: inline` I thought the culprit is in the enmime library. Should I open a bug in inbucket, or will you move it over there?

**Comment by jhillyerd** [comment]
Looks like GitHub won't let me move it, please open a new one, you don't have to put in much detail, just paste the link to this one and I'll take a look. Thanks
