### ISSUE TITLE
Breaking change: do not modify header case?

### ISSUE THREAD

**Issue by jhillyerd** [jhillyerd/enmime#290]
`net/textproto` modifies header cases, for example:
- `MIME-version:` -> `Mime-Version:` (`IME` are lower cases, `v` is upper case)
- `Message-ID:` -> `Message-Id:` (`d` is lower case)

Question for you:

1. Should we do case convert in this PR to keep enmime backward compatible?
2. Or, we keep original cases in this PR, and use original cases in test cases? This may break backward compatibility. But there's no need to convert cases at all for email headers.

Of course we can tag a new version first with option 1 implemented first, then release a new version with option 2 implemented as a breaking change.

Let me know your opinions and final decision.

_Originally posted by @iredmail in https://github.com/jhillyerd/enmime/issues/283#issuecomment-1464835088_

**Comment by iredmail** [comment]
> Thinking about this, seems like the benefit is being able to recreate the exact case of the headers, but we then have the downside that specific headers would be more difficult to fetch by name?

`net/textproto` modifies header key like `MIME-version:` to `Mime-Version:`, what's the difference if you want to get header value with case insensitive header key like `mime-version`?

**Comment by jhillyerd** [comment]
I think it's best to leave this as is for 1.0, as the canonicalized header names make extracting header values more predictable.

If there is a need to preserve the original header name case, we could add an option or another map to hold the name+values.

**Comment by cgroschupp** [comment]
My anti-spam solution (rspamd) gives a score for case mismatch. https://github.com/rspamd/rspamd/blob/master/rules/headers_checks.lua#L643

It is better to leave the case as it is.

**Comment by jhillyerd** [comment]
If someone wants to contribute it as a parser option, that would be fine.  It's not something I have time to do myself.
