### ISSUE TITLE
Type of the `(*enmime.Part).Header` field is now private

### ISSUE THREAD

**Issue by dcormier** [jhillyerd/enmime#294]
What I did:
I've had a function that returns the `textproto.MIMEHeader` value from the `(*enmime.Part).Header` field.

What I expected:
That I would continue to be able to return that field.

What I got:
After upgrading, the type of that field is now private, so I cannot return it. Instead, I have to manually convert it from the `enimime` internal `MIMEHeader` into the `textproto.MIMEHeader` from the stdlib.

Release or branch I am using:
v1.0.0

This is a result of #283.

**Comment by jhillyerd** [comment]
I'd consider this a bug, we should return the textproto version if we can.

**Comment by jhillyerd** [comment]
@dcormier please take a look at the PR above when you have a minute.

**Comment by dcormier** [comment]
A couple of comments, but it's really up to you. What you have there now would solve what I ran into.
