### ISSUE TITLE
Provide mimes in order

### ISSUE THREAD

**Issue by sethgrid** [jhillyerd/enmime#31]
Per RFC 1341 (https://tools.ietf.org/html/rfc1341):
```
In general, choosing the best type 
means displaying only the LAST part that can  be  displayed.
```
With the current implementation, it is hard to determine mime part ordering. Additionally, enmime drains the content from HTML and text parts, making it hard to interact with each mime part as a whole entity. 

Ideally, the api would allow for something like:
```
# get a slice of mime parts
mimeParts := ReadMime(reader)
for _, part := range mimeParts {
  mapOfHeaders := part.Headers() // map[string][]string
  easyAccessToCommonHeader := part.ContentType() // have other helpers maybe, like "to", "from", or get header slice by string, get charset, etc
  rawBytes := part.RawContent() 
  decoded := part.DecodedContent() // uses the detected charset and content type
}
```
This allows a client to know the order and present the best display and allows for easily parsing the mime entities. Ideally, someone should be able to stitch this information back together and create the (nearly) identical email from the parts.

**Comment by jhillyerd** [comment]
You raise an interesting point.

You can skip most of Enmime's processing by reading the message with:

https://godoc.org/github.com/jhillyerd/enmime#ReadParts

Then calling

https://godoc.org/github.com/jhillyerd/enmime#Part.DepthMatchAll with a matcher that just returns true to get all parts in order.

**Comment by sethgrid** [comment]
DepthMatchAll is handy, I had written my own dfs but I'm happy to use that one :). We are looking around at different mime solutions in Go and hoping we don't have to use CGO with gmime ::fingerscrossed::. Feel free to close the issue at your leisure.

**Comment by jhillyerd** [comment]
#37 took care of the drained MIME parts.  Going to close this.
