### ISSUE TITLE
Epilogue parsing "hidden trap"

### ISSUE THREAD

**Issue by pedrinimm** [jhillyerd/enmime#32]
Normally the Epilogue is an area that should be left blank, and applications should ignore it, which enmime does. 

>These areas should generally be left blank, and implementations should ignore anything that appears before the first boundary or after the last one.
> - rfc1341

Nevertheless, in real life things are not always according to standard. Epilogues are now used by spammers or attackers to insert malicious content into emails, this content comes in the form of other mime parts, these come right after the closing boundary of an email.

```--B_3583309036_620884921--```

This parts are displayed by email clients and when they come with a content disposition of inline for example, clients try execute or render the content. 

Anyway. It would be nice to extend enmime in a way that it could perform beyond boundary mime parsing , after finding the "last" closing boundary. Perform a last check and search for other parseable content. Because when the parts are extracted to perform further analysis like malware analysis, the attachments on the epilogue are ignored and forwarded to the end user. And there is no way we can be aware of their existence before hand.

**Comment by els0r** [comment]
This bug was spotted when parsing the attached sample (strip .txt if you want it displayed in a Mail client). It is from the Enron dataset.

This issue is relevant since several Mail clients wrongfully display content in the Epilogue, hence exposing possibly malicious content.
[doc_with_broken_boundary.sample.txt](https://github.com/jhillyerd/enmime/files/1161592/doc_with_broken_boundary.sample.txt)

**Comment by jhillyerd** [comment]
Some thought would have to be put into how to implement this.  We could add a Part.Epilogue flag, and add them as a Part.NextSibling to the last valid part, but that could cause unmodified Enmime clients to start displaying that content.

**Comment by els0r** [comment]
Thanks for getting back on this so quickly.

The existing clients should not have to adapt their code, but we could add additional functionality for those who want to enforce policies/further processing based on the existence of Epilogue data.

Having access to a flag `Part.Epilogue` would certainly help to define such policies. It could be set every time the parser notices that the Reader still has data after all RFC compliant MIME boundaries have been read.

Optimal would be to configure the Parser to choose either parsing behavior:
* ignore epilogue (default)
* throw error upon existing Epilogue data (alert mode)
* attempt to parse Epilogue data (advanced parsing mode)

Would it be feasible to wrap an `EnvelopeReader` that can be configured to implement above behavior? It could be instantiated with a functional option `WithEpilogueHandler( ... )` that governs how/if Epilogue data is parsed.

Existing clients would still use the standard `ReadEnvelope` method while Epilogue-savvy clients could use the `EnvelopeReader` instead.

**Comment by jhillyerd** [comment]
Has been merged to master.
