### ISSUE TITLE
Base64 decoding error

### ISSUE THREAD

**Issue by Requaos** [jhillyerd/enmime#34]
I have an email attachment that is being mishandled. Its a curious thing, probably some funky counting issue with the padding chars.

After some investigation I found that during the buffer sizing, or resizing, it is dropping the last quad of the base64 string... string input length is 12992, but only 12988 characters are being fed to the decoder OR the receiving buffer is sized to 9615 instead of the 9617, causing the last two bytes to be trimmed from the tail of the byte stream.

I don't know precisely which copy operation is causing the miscount and to be fare I have a service running with your processing engine and this fringe case is one out of 60,000 emails with an average of 3 attachments per. 

other files process fine... perhaps we could take this offline to exchange my sample file because it contains confidential information and review it in attempt to reproduce the issue with a benign file exhibiting the same features.

fyi, I am able to decode the blob accurately using this:
```
f, _ := ioutil.ReadFile("base64.txt")
base64Bytes, _ := base64.StdEncoding.DecodeString(string(f))
file, _ := os.Create("decoded.xlsx")
defer file.Close()
writer := bufio.NewWriter(file)
writer.Write(base64Bytes)
defer writer.Flush()
```

Thoughts?

**Comment by jhillyerd** [comment]
Apologies for not responding, overloaded at work.  This may be fixed in #43 (not yet merged), the tl;dr is enmime is incorrectly attempting to UTF-8 decode binary content.

**Comment by Requaos** [comment]
Cool, I have a local repo setup to reproduce this bug, so when the fix is pushed to an issue branch, I can test to verify that it is resolved before merging with master

**Comment by jhillyerd** [comment]
I've merged #43 into `develop` branch; give it a shot and let me know.

**Comment by Requaos** [comment]
Yeah, it's at work so I'll let you know on Monday afternoon

**Comment by jhillyerd** [comment]
Everything is now merged to master

**Comment by jhillyerd** [comment]
Going to close this, please re-open if you are able to repro the issue.  Alternately, the email listed on my profile is private, so safe to send attachment to.  You may want to ping this bug after emailing in case it goes into spam.
