### ISSUE TITLE
Email's attachment won't be exported correctly.

### ISSUE THREAD

**Issue by leibiao** [jhillyerd/enmime#42]
I try to export an email's attachment(Zip archive), but that exported file could not be unzip successfully.I compare this file to which exported by emali client, like follows:
`50 4B 03 04 14 00 08 00 08 00 EF BF BD 02 29 4A` -->export by enmime
`50 4B 03 04 14 00 08 00 08 00 C2 02 29 4A 00 00` -->export by email client
It's clearly that the byte 'C2' transfers to 'EF BF BD 02', I also check the implementation of Part's Read method:
` 
return p.utf8Reader.Read(b)  
`
OK, maybe it causes the issue when I need to read a binary file. So can export a METHOD for read the decoded binary content?

**Comment by jhillyerd** [comment]
I was able to write a test to reproduce this in 3dae741f77ff413f6e0dc7cd18537ca4e7563f67 - the only catch is that the attachment had to have a charset encoding header - which a ZIP file should not.  Can you check the email that triggered the bug and confirm?

**Comment by leibiao** [comment]
Yes. The reason you point out triggered the bug.Because the zip file's name is not english(other language), this header is used for the name instead of the content.
