### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by fchoquet** [jhillyerd/enmime#58]
Hi!

I'm using this excellent library on one of my project. I'm happy with it, but unfortunately upgrading dependencies breaks my code every now and then.
I know it's still a beta, but I think it would be great to create releases to help dependency management. 

Of course I can still pin the commit hash but this is suboptimal. When a BC is introduced I have to try all the intermediate commit hashes between the version I've pinned and the latest release to find the most recent compatible version. This process would be a lot easier with SemVer.

Thanks for your help on this. And thanks again for all your work on this library!

**Comment by jhillyerd** [comment]
Thanks for the feedback.  I had been avoiding this as I didn't want to maintain a change log while the code was still in heavy flux.  It's also difficult to tell how many people are using enmime, it seems to be more popular in the enterprise than in the open source community.

I do agree with you, enmime is at a point where it's reasonable to start versioning releases.  I will start the process.

**Comment by jhillyerd** [comment]
BAM! https://github.com/jhillyerd/enmime/releases

**Comment by fchoquet** [comment]
Awesome! Thanks!
