### ISSUE TITLE
Add Encode(io.Writer) method to enmime.Envelope

### ISSUE THREAD

**Issue by jhillyerd** [jhillyerd/enmime#7]
Implement the ability to create an email with enmime.

Envelope.Encode() should write out a well formed MIME email, providing the Envelope and its associate parts are properly configured.

Other work will need to be done, such as generating unique MIME part boundary strings.

**Comment by jhillyerd** [comment]
Blocked on #50

**Comment by jhillyerd** [comment]
Now that Part encoding (#50) is almost finished, I've been giving this some more thought.  enmime.Envelope itself doesn't add much value in terms of creating a new message, the user still has to manipulate headers directly.

It makes more sense just to implement a fluent builder.

**Comment by bronger** [comment]
I need to read an email from a file, manipulate it, and send it. AFAICS, this is not possible with enmime because the Envelope wouldn’t send and the Builder wouldn’t read, and there is no converter between them, right?

**Comment by jhillyerd** [comment]
Not yet.  #158 is tracking a feature along these lines.

**Comment by bronger** [comment]
`myEnvelope.Root.Encode()` looks pretty much like the mail that I read from the file (apart from ordering of headers). It is truly equivalent?

**Comment by jhillyerd** [comment]
That should be close, enmime may convert other charsets to UTF-8.  But essentially my plan is to update Envelope header manipulation methods to also update that Root part, and leverage Encode() to send the message.

If you do run into any issues, maybe add them to #158 so I keep them in mind when implementing.
