### ISSUE TITLE
Attachments on emails originating from Exchange server failing to parse.

### ISSUE THREAD

**Issue by smashedtoatoms** [jhillyerd/enmime#70]
__What I did:__ Tried to parse email with video and manifest attachments from an exchange server

__What I expected:__ I expected the attachments to parse

__What I got:__ `Failed to ReadParts: illegal base64 data at input byte 0`

Release or branch I am using: master at bed8d3f

The payload is huge because the attachment is about 5MB; however, if it would help, I have no issue sending it to you.  I have tried to figure out what is going on, but I haven't had much luck.  If I send it from a non-exchange email source, it works fine.  Any ideas on what might be going on?  This is my first foray into email parsing, and not shockingly, Microsoft is making it horrible.  Thanks for any help that you can provide.

**Comment by jhillyerd** [comment]
I'd be interested to see it, as I haven't heard of issues from Exchange.  If you could zip it up and send to github@hillyerd.com I will take a look.

**Comment by smashedtoatoms** [comment]
Ok, it is on its way.

**Comment by smashedtoatoms** [comment]
Ugh, this is totally user-error.  I was passing it a ReadCloser from which the contents had already been read.  When I am not a total moron, it seems to work fine.  Sorry to waste your time.
