### ISSUE TITLE
Make Base64Cleaner optional

### ISSUE THREAD

**Issue by nerdlich** [jhillyerd/enmime#75]
Having the Base64Cleaner might be a good idea in many cases, but it can also be problematic, because "dirty" base64 can be used to obfuscate malware (see [1], where Step 4 does not produce a parsing error with enmime). Therefore, would it make sense to introduce a flag that allows to disable usage of the cleaner?

What I did:
Parsed eml from Step 4 on [1].

What I expected:
Parsing error (as the core base64 decoder would return)

What I got:
No parsing error

Release or branch I am using:
develop

[1] https://noxxi.de/research/mime-5-easy-steps-to-bypass-av.html

**Comment by jhillyerd** [comment]
Interesting.  Seems like there are two possible approaches, the easy/hacky way via a global flag (not threadsafe if a program wants to try parsing both ways), and the hard/flexible way with some sort of options structure being passed into enmime.

I'd prefer not to change the API again, so we shouldn't add options to the existing ReadEnvelope and ReadParts functions.

**Comment by riddlesomebody** [comment]
@nerdlich I think enmime has the ability to handle this case(Step 4) you refer. You can review the code as follows,which uses `RawStdEncoding ` that has omitted '=' other than `StdEncoding`.
<https://github.com/jhillyerd/enmime/blob/bed8d3f5e62dd8aca071dfe08f775f17e3647dd7/part.go#L179>

**Comment by nerdlich** [comment]
@riddlesomebody not sure I understand what you mean. You are always using the b64cleaner:

    // Base64Cleaner improves the tolerance of in Go's built-in base64 decoder by stripping out
    // characters that would cause decoding to fail.
    type Base64Cleaner struct {

**Comment by riddlesomebody** [comment]
@nerdlich Maybe you should review the implement of `Base64Cleaner`.I had strengthened it for dirty data decoding, and now `Base64Cleaner` would do it best to decode the dirty data as the most part of major email clients do, even if an error occurs.
If it wouldn't decode dirty data correctly, I think even malware payload would be broken, which is also nonsense for malware author. So why do you want to disable the function you want?

**Comment by riddlesomebody** [comment]
@jhillyerd Maybe `func (bc *Base64Cleaner) Read(p []byte) (n int, err error)` should return a error that will not interrupt the  process of base64 decoding.

**Comment by jhillyerd** [comment]
The base64 cleaner already has a path to bubble up non-fatal errors: https://github.com/jhillyerd/enmime/blob/bed8d3f5e62dd8aca071dfe08f775f17e3647dd7/part.go#L220

I'm definitely not opposed to giving callers a way to disable the cleaner, but I generally don't do much development during the summer months.  Especially not now, in the middle of a heat wave where I live. :)

**Comment by nerdlich** [comment]
That's a great point, I will check that out.

**Comment by nerdlich** [comment]
Not an issue anymore, thanks for pointing this out.
