### ISSUE TITLE
Inconsistent use of Ptrs for error types

### ISSUE THREAD

**Issue by jhorowitz** [jhillyerd/enmime#79]
What I did:
N/A

What I expected:
I expect to always receive an Error or and *Error but the Envelope type has a `[]*Error` and the Part type has a `[]Error`

What I got:
N/A

Release or branch I am using:
Master

(Please attach a sample message if you feel it will help reproduce the issue)

```go
// Envelope is a simplified wrapper for MIME email messages.
type Envelope struct {
	...
	Errors      []*Error              // Errors encountered while parsing
	...
}
```

```go
// Part represents a node in the MIME multipart tree.  The Content-Type, Disposition and File Name
// are parsed out of the header for easier access.
type Part struct {
	...
	Errors      []Error              // Errors encountered while parsing this part
	...
}
```

I'm happy to make a PR if you agree that this is something which should be addressed. Thanks for the great library, btw!

**Comment by jhillyerd** [comment]
Will have to do a bit of research and see if I had a good reason for doing it this way, I do not remember.

I did some work in `develop` to satisfy Go error interface #60 - but it looks like it still uses a mix of pointer and value types.
