### ISSUE TITLE
Investigate double quote surrounded encoded words in headers

### ISSUE THREAD

**Issue by jhillyerd** [jhillyerd/enmime#80]
While writing Inbucket tests, I noticed that `"` is leaking into address names.

Got: "Test of ȇɲʢȯȡɪɴʛ" <recipient@inbucket.org>
Want: Test of ȇɲʢȯȡɪɴʛ <recipient@inbucket.org>

Version: enmime v0.2.1

**Comment by jhillyerd** [comment]
I think this was the case that triggered it: [sample.txt](https://github.com/jhillyerd/enmime/files/2631753/sample.txt)

It doesn't repro with the current development branch, let me try with 0.2.1.

**Comment by jhillyerd** [comment]
Hmm, 0.2.1 doesn't seem to do it either (using `cmd/mime-dump` for both), it be an issue with Inbucket then.

**Comment by requaos** [comment]
If this is not currently reproducible, may we close this issue?
