### ISSUE TITLE
Support for decoding options

### ISSUE THREAD

**Issue by jhillyerd** [jhillyerd/enmime#90]
It would be nice to have a way to pass options during the decoding process.   Potential examples:

- Strict decoding: fail if message is malformed.
- Should character sets be converted to UTF-8?
- Performance options

This would likely either be an options struct (with sane defaults), or use the functional options pattern.

An options struct would allow re-use, but functional pattern would have less API impact.

**Comment by dcormier** [comment]
> [...]or use the functional options pattern.

☝️

That pattern is certainly my preference, for what it's worth.

**Comment by requaos** [comment]
As far as implementing variable tolerance, I imagine that methods on the errors slice type could selectively panic on the insert of an error with severity higher than the specified tolerance level.

**Comment by jhillyerd** [comment]
Closed by #248
