### ISSUE TITLE
Part.Encode() adds an extra newline

### ISSUE THREAD

**Issue by dann7387** [jhillyerd/enmime#99]
What I did:
- Place string into a "text/plain" Part.
- Use Part.Encode() to write object to buffer
- Use Part.ReadParts() to read the buffer back into a Part object
- Read the Content field of the new object

```
package main

import (
        "bytes"
        "fmt"
        "github.com/jhillyerd/enmime"
)

func main() {
        var buf bytes.Buffer
        text := "This is my message."
        p := enmime.NewPart("text/plain")
        p.Content = []byte(text)

        p.Encode(&buf)
        p1, _ := enmime.ReadParts(&buf)

        fmt.Printf("\"%s\"", string(p1.Content))
}
```

What I expected:
Expected the resulting string to be exactly the same as the original.
```
"This is my message."
```

What I got:
Extra new line (\r\n) at the end of the string
```
"This is my message.
"
```

Release or branch I am using:
master

(Please attach a sample message if you feel it will help reproduce the issue)

**Comment by jhillyerd** [comment]
https://travis-ci.org/jhillyerd/enmime/builds/461121525

Build broke on travis.

**Comment by jhillyerd** [comment]
Ah, I think it's because the `testdata/encode/part-file-mod-date.golden` was added in a different commit.  will fix now.
